# Generated by Django 6.0 on 2026-01-11 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gosh_main", "0002_aboutblock_category_contactinfo_contactmessage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="contactinfo",
            name="image",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="extra",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="aboutblock",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Static path under static/ (e.g. 'gosh_main/images/foo.jpg')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="organisation",
            field=models.CharField(default="Goshen Giant Food", max_length=255),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Static path under static/ (e.g. 'gosh_main/images/foo.jpg')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="author_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="gosh_main.product",
            ),
            preserve_default=False,
        ),
    ]
