# Generated by Django 6.0 on 2026-03-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gosh_main", "0010_revised_product_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("NG", "Nigeria"),
                            ("US", "United States"),
                            ("UK", "United Kingdom"),
                            ("CA", "Canada"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("IT", "Italy"),
                            ("ES", "Spain"),
                        ],
                        default="NG",
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.CharField(
                        blank=True,
                        help_text="URL or static path to company logo",
                        max_length=255,
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(
                        blank=True,
                        help_text="URL template for tracking (e.g., https://company.com/track/)",
                    ),
                ),
                (
                    "coverage_states",
                    models.JSONField(
                        default=list,
                        help_text="List of states/regions covered by this company",
                    ),
                ),
                (
                    "base_shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base shipping cost",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "country")},
            },
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        help_text="Unique tracking number from logistics company",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "current_location_lat",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Current latitude of package",
                        max_digits=9,
                    ),
                ),
                (
                    "current_location_lng",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Current longitude of package",
                        max_digits=9,
                    ),
                ),
                (
                    "current_location_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable location name",
                        max_length=255,
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Destination latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Destination longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("warehouse", "At Warehouse"),
                            ("in_transit", "In Transit"),
                            ("arrived_hub", "Arrived at Hub"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                        ],
                        default="warehouse",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateTimeField(
                        blank=True,
                        help_text="Estimated delivery date and time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "logistics_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracked_orders",
                        to="gosh_main.logisticscompany",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking",
                        to="gosh_main.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("warehouse", "At Warehouse"),
                            ("in_transit", "In Transit"),
                            ("arrived_hub", "Arrived at Hub"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                        ],
                        default="in_transit",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Message about this update",
                        max_length=255,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="gosh_main.ordertracking",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tracking Histories",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
